# -*- coding: utf-8 -*-
"""calc_execution_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MsKjgBjqs9v8G-MMSQKu4ecD8ZRvKMG
"""

import argparse
import pandas as pd
import numpy as np
import sys

def CalculateMetrics(input_file: str, output_file: str):
    try:
        df = pd.read_csv(input_file)
    except FileNotFoundError:
        print(f"File Not Found '{input_file}'")
        sys.exit(1)

    df['OrderTransactTime'] = pd.to_datetime(df['OrderTransactTime'])
    df['ExecutionTransactTime'] = pd.to_datetime(df['ExecutionTransactTime'])
    df['LimitPrice'] = pd.to_numeric(df['LimitPrice'])
    df['AvgPx'] = pd.to_numeric(df['AvgPx'])
    df['Side'] = pd.to_numeric(df['Side'])
    df['ExecSpeedSecs'] = (df['ExecutionTransactTime'] - df['OrderTransactTime']).dt.total_seconds()

    BetterBuy = df['LimitPrice'] - df['AvgPx']
    BetterSell = df['AvgPx'] - df['LimitPrice']


    df['PriceImprovement'] = np.where(df['Side'] == 1, BetterBuy, BetterSell)


    df['PriceImprovement'] = df['PriceImprovement'].clip(lower=0)

    Metrics = df.groupby('LastMkt').agg(
        AvgPriceImprovement=('PriceImprovement', 'mean'),
        AvgExecSpeedSecs=('ExecSpeedSecs', 'mean')
    ).reset_index()

    Metrics.to_csv(output_file, index=False, float_format='%.15f')



def main():
    parser = argparse.ArgumentParser(
        description="Calculate Matrics"
    )
    parser.add_argument(
        '--input_csv_file',
        required=True,
    )
    parser.add_argument(
        '--output_metrics_file',
        required=True,
    )
    args = parser.parse_args()
    CalculateMetrics(args.input_csv_file, args.output_metrics_file)


if __name__ == "__main__":
    main()